import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

/**
 * POST /api/lists/[id]/share — Create a share link for a list (owner only)
 * GET  /api/lists/[id]/share — List existing shares for a list (owner only)
 */

export async function POST(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: listId } = await params
    const supabase = await createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Verify ownership
    const { data: list, error: listError } = await supabase
      .from('lists')
      .select('id, user_id')
      .eq('id', listId)
      .single()

    if (listError || !list) {
      return NextResponse.json({ error: 'List not found' }, { status: 404 })
    }
    if (list.user_id !== user.id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    // Create the share (token is auto-generated by the database default)
    const { data: share, error: shareError } = await supabase
      .from('list_shares')
      .insert({ list_id: listId, created_by: user.id })
      .select('id, token, permission, created_at, expires_at')
      .single()

    if (shareError) {
      return NextResponse.json(
        { error: shareError.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      ...share,
      url: `/lists/${listId}?token=${share.token}`,
    })
  } catch (error: unknown) {
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : 'Internal server error',
      },
      { status: 500 }
    )
  }
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: listId } = await params
    const supabase = await createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // RLS ensures only owner sees their shares
    const { data: shares, error } = await supabase
      .from('list_shares')
      .select('id, token, permission, created_at, expires_at')
      .eq('list_id', listId)
      .eq('created_by', user.id)
      .order('created_at', { ascending: false })

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({
      shares: (shares ?? []).map((s) => ({
        ...s,
        url: `/lists/${listId}?token=${s.token}`,
      })),
    })
  } catch (error: unknown) {
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : 'Internal server error',
      },
      { status: 500 }
    )
  }
}
